<?php
session_start();
define("LOGIN_PAGE","login.php");
define("QUIZ_ERROR","quiz_error.php");
define("AUTHENTICATED_HOME","home.php");
define("AUTH_WEBSERVICE","http://cnmt310.braingia.org/authws/auth.php");
define("QUESTION_WEBSERVICE","https://cnmt310.braingia.org/qws/q.php");
define("APIKEY","ijv3pwjov");
define("APIUSER","user22");
